name: Test, Lint & Types

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: node:10.16-jessie

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install

  test:
    needs: install
    runs-on: ubuntu-latest
    container: node:10.16-jessie

    steps:
    - name: test
      run: npm run test:ci
      env:
        CI: true

  lint:
    needs: install
    container: node:10.16-jessie
    runs-on: ubuntu-latest

    steps:
    - name: lint
      run: npm run lint
      env:
        CI: true

  types:
    needs: install
    container: node:10.16-jessie
    runs-on: ubuntu-latest

    steps:
    - name: types
      run: npm run types
      env:
        CI: true
