name: CI

on: [push]

jobs:
  install:
    container:
      image: node:10.16-jessie

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install
      env:
        CI: true

  lint:
    needs: install

    container:
      image: node:10.16-jessie

    steps:
    - name: lint
      run: npm run lint
      env:
        CI: true

  test:
    needs: install

    container:
      image: node:10.16-jessie

    steps:
    - name: test
      run: npm run test:ci
      env:
        CI: true
